<a href="https://colab.research.google.com/github/yashica12/Neural-Networks/blob/master/First_ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
!pip install -q keras


In [0]:
!pip install -q theano

In [0]:
from google.colab import drive
drive.mount('/content/drive/')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive/


Data Preprocessing

In [0]:

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the datase
dataset = pd.read_csv('/content/drive/My Drive/Colab Notebooks/Churn_Modelling.csv')


In [0]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [0]:
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values



Encoding the variables - Country and Gender 


In [0]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_1.fit_transform(X[:, 2])

onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()

In [0]:
X

array([[1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [0]:
X=X[:,1:]

Preparing Training and Test dataset 


In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)


In [0]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

array([[-0.5698444 ,  1.74309049,  0.16958176, -1.09168714, -0.46460796,
         0.00666099, -1.21571749,  0.8095029 ,  0.64259497, -1.03227043,
         1.10643166],
       [ 1.75486502, -0.57369368, -2.30455945,  0.91601335,  0.30102557,
        -1.37744033, -0.00631193, -0.92159124,  0.64259497,  0.9687384 ,
        -0.74866447],
       [-0.5698444 , -0.57369368, -1.19119591, -1.09168714, -0.94312892,
        -1.031415  ,  0.57993469, -0.92159124,  0.64259497, -1.03227043,
         1.48533467],
       [-0.5698444 ,  1.74309049,  0.03556578,  0.91601335,  0.10961719,
         0.00666099,  0.47312769, -0.92159124,  0.64259497, -1.03227043,
         1.27652776],
       [-0.5698444 ,  1.74309049,  2.05611444, -1.09168714,  1.73658844,
         1.04473698,  0.8101927 ,  0.8095029 ,  0.64259497,  0.9687384 ,
         0.55837842],
       [ 1.75486502, -0.57369368,  1.29325423, -1.09168714, -0.17749539,
        -1.031415  ,  0.44253504,  0.8095029 ,  0.64259497, -1.03227043,
         1.632

In [0]:
import keras

Using TensorFlow backend.


In [0]:
from keras.models import Sequential

In [0]:
from keras.layers import Dense

Building classifier 


In [0]:
classifier = Sequential()

In [0]:
classifier.add(Dense(output_dim=6, init='uniform', activation='relu' , input_dim=11))

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [0]:
classifier

In [0]:
classifier.add(Dense(units=6, init='uniform', activation='relu' ))

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=6, activation="relu", kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [0]:
classifier.add(Dense(output_dim=1, init='uniform', activation='sigmoid'))

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [0]:
classifier.compile(optimizer = 'adam' , loss = 'binary_crossentropy' , metrics = ['accuracy'])

In [0]:
classifier.fit(X_train,y_train,batch_size=10,nb_epoch=100)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """Entry point for launching an IPython kernel.


Epoch 1/100
8000/8000 [==============================] - 5s 684us/step - loss: 0.4939 - acc: 0.7960
Epoch 2/100
8000/8000 [==============================] - 5s 579us/step - loss: 0.4296 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 5s 586us/step - loss: 0.4245 - acc: 0.7960
Epoch 4/100
8000/8000 [==============================] - 5s 583us/step - loss: 0.4208 - acc: 0.8054
Epoch 5/100
8000/8000 [==============================] - 5s 582us/step - loss: 0.4178 - acc: 0.8230
Epoch 6/100
8000/8000 [==============================] - 5s 582us/step - loss: 0.4157 - acc: 0.8264
Epoch 7/100
8000/8000 [==============================] - 5s 582us/step - loss: 0.4142 - acc: 0.8300
Epoch 8/100
8000/8000 [==============================] - 5s 581us/step - loss: 0.4126 - acc: 0.8307
Epoch 9/100
8000/8000 [==============================] - 5s 578us/step - loss: 0.4112 - acc: 0.8322
Epoch 10/100
8000/8000 [==============================] - 5s 578us/step - loss: 0.4100 - acc: 0.8325

In [0]:
y_pred = classifier.predict(X_test)

In [0]:
y_pred

array([[0.16177587],
       [0.32025877],
       [0.11923895],
       ...,
       [0.18270157],
       [0.1222826 ],
       [0.12263938]], dtype=float32)

In [0]:
y_pred = (y_pred>0.5)

In [0]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [0]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [0]:
cm

array([[1548,   47],
       [ 270,  135]])

In [0]:
accuracy_test = (1548+135)/2000

In [0]:
accuracy_test

0.8415

In [0]:
new_predict = classifier.predict(sc.transform(np.array([[0,0,600,1,40,3,6000,2,1,1,50000]])))

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [0]:
new_predict

array([[0.05519238]], dtype=float32)

In [0]:
new_predict = (new_predict>0.5)

In [0]:
new_predict

array([[False]])